branches:
  only:
  - master

matrix:
  include:
    # build documentation
    language: python
    sudo: disabled
    install:
      - pip install plantuml
    script:
      - ./scripts/build-docs.sh
    after_success:
      - ./scripts/push-docs.sh