branches:
  only:
  - master
  - develop

matrix:
  include:
    # build documentation
    - language: python
      sudo: disabled
      install:
        - pip install plantuml
      script:
        - make docs
    # run tests
    - language: go
      go:
        - "1.11"
      sudo: disabled
      before_install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      install:
        - dep ensure
      script:
        - make test