// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdbInterface is an autogenerated mock type for the AdbInterface type
type AdbInterface struct {
	mock.Mock
}

// Run provides a mock function with given fields: device, args
func (_m *AdbInterface) Run(device string, args []string) (string, error) {
	ret := _m.Called(device, args)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = rf(device, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(device, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
